name: Spellcheck (typos)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install typos
        uses: taiki-e/install-action@v2
        with:
          tool: typos
      - name: Run typos
        run: typos .
